package database

import (
	"github.com/lib/pq"
	"github.com/metafusion/metafusion-app/internal/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func seedRelationTypes(db *gorm.DB) {
	rows := []models.RelationType{
		{
			Code: "part_of_franchise", Domain: "work_franchise",
			NameZh: "企划归属", NameEn: "Part of Franchise",
			Names: models.JSONB{"zh-CN": "企划归属", "en-US": "Part of Franchise"},
			Description: "作品、子企划或主体归属于某跨媒介企划/世界观",
			ForwardLabelZh: "属于企划", ReverseLabelZh: "企划包含",
			ForwardLabelEn: "is part of franchise", ReverseLabelEn: "contains",
			AllowedSourceTypes: pq.StringArray{"work", "franchise", "artist", "person", "group", "fictional_band", "virtual_character", "label", "studio", "publisher", "circle"},
			AllowedTargetTypes: pq.StringArray{"franchise"},
			IsHierarchical: true, Color: "indigo", Icon: "Layers", SortOrder: 306, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "unofficial_of", Domain: "work_work",
			NameZh: "非官方 / 同人衍生", NameEn: "Unofficial Of",
			Names: models.JSONB{"zh-CN": "非官方衍生", "en-US": "Unofficial Of"},
			Description: "网络上传、未出版或同人作品相对于官方作品",
			ForwardLabelZh: "为该作的非官方衍生", ReverseLabelZh: "拥有非官方衍生",
			ForwardLabelEn: "is unofficial of", ReverseLabelEn: "has unofficial derivative",
			AllowedSourceTypes: pq.StringArray{"work"}, AllowedTargetTypes: pq.StringArray{"work"},
			Color: "rose", Icon: "GitFork", SortOrder: 335, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "imprint_of", Domain: "agent_franchise",
			NameZh: "企划子厂牌 / 品牌", NameEn: "Imprint Of",
			Names: models.JSONB{"zh-CN": "企划子厂牌", "en-US": "Imprint Of"},
			Description: "音乐厂牌或子品牌隶属于某跨媒介企划",
			ForwardLabelZh: "为该企划的厂牌/品牌", ReverseLabelZh: "旗下厂牌",
			ForwardLabelEn: "is imprint of", ReverseLabelEn: "has imprint",
			AllowedSourceTypes: pq.StringArray{"label", "publisher", "studio", "artist"},
			AllowedTargetTypes: pq.StringArray{"franchise"},
			IsHierarchical: true, Color: "teal", Icon: "Disc", SortOrder: 55, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "alternate_form_of", Domain: "agent_agent",
			NameZh: "角色变体 / 形态", NameEn: "Alternate Form Of",
			Names: models.JSONB{"zh-CN": "角色变体", "en-US": "Alternate Form Of"},
			Description: "同一角色的不同形态",
			ForwardLabelZh: "为该角色的变体", ReverseLabelZh: "拥有变体形态",
			ForwardLabelEn: "is alternate form of", ReverseLabelEn: "has alternate form",
			AllowedSourceTypes: pq.StringArray{"virtual_character"}, AllowedTargetTypes: pq.StringArray{"virtual_character"},
			Color: "purple", Icon: "Sparkles", SortOrder: 37, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "crossover_with", Domain: "work_work",
			NameZh: "跨界联动", NameEn: "Crossover With",
			Names: models.JSONB{"zh-CN": "跨界联动", "en-US": "Crossover With"},
			Description: "作品或企划之间的联动活动",
			ForwardLabelZh: "联动于", ReverseLabelZh: "联动于",
			ForwardLabelEn: "crossovers with", ReverseLabelEn: "crossovers with",
			AllowedSourceTypes: pq.StringArray{"work", "franchise"}, AllowedTargetTypes: pq.StringArray{"work", "franchise"},
			IsSymmetric: true, Color: "amber", Icon: "Handshake", SortOrder: 336, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "creator_of", Domain: "agent_franchise",
			NameZh: "世界观原作 / 创企划", NameEn: "Creator Of Franchise",
			Names: models.JSONB{"zh-CN": "创企划", "en-US": "Creator Of"},
			Description: "作者或团队创立可被衍生的世界观/企划",
			ForwardLabelZh: "创立了企划", ReverseLabelZh: "企划原作为",
			ForwardLabelEn: "created franchise", ReverseLabelEn: "was created by",
			AllowedSourceTypes: pq.StringArray{"person", "group", "studio", "circle", "artist"},
			AllowedTargetTypes: pq.StringArray{"franchise"},
			Color: "emerald", Icon: "Award", SortOrder: 38, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "included_in", Domain: "work_work",
			NameZh: "收录于", NameEn: "Included In",
			Names: models.JSONB{"zh-CN": "收录于", "en-US": "Included In"},
			Description: "单曲或曲目母版被专辑/合集收录",
			ForwardLabelZh: "收录于", ReverseLabelZh: "收录了",
			ForwardLabelEn: "is included in", ReverseLabelEn: "includes",
			AllowedSourceTypes: pq.StringArray{"work", "canonical_entry"}, AllowedTargetTypes: pq.StringArray{"work"},
			Color: "cyan", Icon: "Disc", SortOrder: 337, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "expansion_of", Domain: "work_work",
			NameZh: "资料片 / 扩展", NameEn: "Expansion Of",
			Names: models.JSONB{"zh-CN": "资料片", "en-US": "Expansion Of"},
			Description: "独立发售的 DLC/资料片相对于本体作品",
			ForwardLabelZh: "为该作的资料片", ReverseLabelZh: "拥有资料片",
			ForwardLabelEn: "is expansion of", ReverseLabelEn: "has expansion",
			AllowedSourceTypes: pq.StringArray{"work"}, AllowedTargetTypes: pq.StringArray{"work"},
			Color: "sky", Icon: "PackagePlus", SortOrder: 338, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "soundtrack_of", Domain: "work_work",
			NameZh: "原声带 / 音乐集", NameEn: "Soundtrack Of",
			Names: models.JSONB{"zh-CN": "原声带", "en-US": "Soundtrack Of"},
			Description: "影视、游戏、动画的音乐原声带或配乐集关联至原作本体",
			ForwardLabelZh: "为该作的原声带", ReverseLabelZh: "拥有原声音乐",
			ForwardLabelEn: "is soundtrack of", ReverseLabelEn: "has soundtrack",
			AllowedSourceTypes: pq.StringArray{"work"}, AllowedTargetTypes: pq.StringArray{"work"},
			Color: "emerald", Icon: "Music", SortOrder: 331, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "adaptation_of", Domain: "work_work",
			NameZh: "改编自", NameEn: "Adaptation Of",
			Names: models.JSONB{"zh-CN": "改编自", "en-US": "Adaptation Of"},
			Description: "跨媒介改编作品（如小说改编为动画、漫画改编为真人电影）",
			ForwardLabelZh: "改编自", ReverseLabelZh: "被改编为",
			ForwardLabelEn: "is adaptation of", ReverseLabelEn: "has adaptation",
			AllowedSourceTypes: pq.StringArray{"work"}, AllowedTargetTypes: pq.StringArray{"work"},
			Color: "indigo", Icon: "Layers", SortOrder: 332, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "sequel_of", Domain: "work_work",
			NameZh: "正统续作", NameEn: "Sequel Of",
			Names: models.JSONB{"zh-CN": "正统续作", "en-US": "Sequel Of"},
			Description: "按时间线或叙事主线的后续正传作品",
			ForwardLabelZh: "为该作的续作", ReverseLabelZh: "拥有前作",
			ForwardLabelEn: "is sequel of", ReverseLabelEn: "has prequel",
			AllowedSourceTypes: pq.StringArray{"work"}, AllowedTargetTypes: pq.StringArray{"work"},
			Color: "blue", Icon: "ArrowRight", SortOrder: 333, IsSystem: true, IsEnabled: true,
		},
		{
			Code: "spin_off_of", Domain: "work_work",
			NameZh: "外传 / 衍生作品", NameEn: "Spin-off Of",
			Names: models.JSONB{"zh-CN": "衍生作品", "en-US": "Spin-off Of"},
			Description: "共享同一世界观但独立成篇的外传或番外",
			ForwardLabelZh: "为该作的外传/衍生", ReverseLabelZh: "拥有外传/衍生",
			ForwardLabelEn: "is spin-off of", ReverseLabelEn: "has spin-off",
			AllowedSourceTypes: pq.StringArray{"work"}, AllowedTargetTypes: pq.StringArray{"work"},
			Color: "amber", Icon: "GitFork", SortOrder: 334, IsSystem: true, IsEnabled: true,
		},
	}
	for _, row := range rows {
		_ = db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "code"}},
			UpdateAll: true,
		}).Create(&row).Error
	}
	_ = db.Model(&models.RelationType{}).Where("code = ?", "member_of").Updates(map[string]interface{}{
		"allowed_source_types": pq.StringArray{"person", "virtual_character"},
		"allowed_target_types": pq.StringArray{"group", "orchestra", "studio", "circle", "publisher", "fictional_band"},
	}).Error
	_ = db.Model(&models.RelationType{}).Where("code = ?", "character_in").Updates(map[string]interface{}{
		"allowed_source_types": pq.StringArray{"virtual_character"},
		"allowed_target_types": pq.StringArray{"work", "franchise"},
	}).Error
	_ = db.Model(&models.RelationType{}).Where("code = ?", "collaborates_with").Updates(map[string]interface{}{
		"allowed_source_types": pq.StringArray{"person", "group", "orchestra", "studio", "publisher", "circle", "label", "fictional_band", "virtual_character"},
		"allowed_target_types": pq.StringArray{"person", "group", "orchestra", "studio", "publisher", "circle", "label", "fictional_band", "virtual_character"},
	}).Error
	_ = db.Exec(`UPDATE relation_types SET attribute_schema = $1::jsonb, updated_at = NOW() WHERE code = 'voice_actor_of'`,
		`[{"key": "locale", "type": "string", "label": "配音语种"}, {"key": "region", "type": "string", "label": "地区"}, {"key": "character_name", "type": "string", "label": "角色全名"}, {"key": "is_original_cast", "type": "boolean", "label": "初代/原案声优"}]`).Error
	_ = db.Model(&models.RelationType{}).Where("code = ?", "producer").Updates(map[string]interface{}{
		"allowed_source_types": pq.StringArray{"person", "studio", "publisher", "label"},
	}).Error
	_ = db.Model(&models.RelationType{}).Where("code = ?", "performer").Updates(map[string]interface{}{
		"allowed_source_types": pq.StringArray{"person", "group", "orchestra", "label", "fictional_band"},
	}).Error
	_ = db.Model(&models.RelationType{}).Where("code = ?", "member_of").Updates(map[string]interface{}{
		"allowed_source_types": pq.StringArray{"person", "virtual_character"},
		"allowed_target_types": pq.StringArray{"group", "orchestra", "studio", "circle", "publisher", "fictional_band"},
	}).Error
}

func seedExternalDatabaseDefinitions(db *gorm.DB) {
	defs := []models.ExternalDatabaseDefinition{
		{
			Code: "wikipedia", NameZh: "维基百科", NameEn: "Wikipedia",
			Names: models.JSONB{"zh-CN": "维基百科", "en-US": "Wikipedia", "ja": "ウィキペディア"},
			Category: "all", URLPattern: "https://zh.wikipedia.org/wiki/{id}",
			Icon: "Globe", ValidationRegex: "",
			Description: "全球多语言自由百科全书（填词条标题或完整 URL）",
			SortOrder: 10, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "wikidata", NameZh: "维基数据", NameEn: "Wikidata",
			Names: models.JSONB{"zh-CN": "维基数据", "en-US": "Wikidata"},
			Category: "all", URLPattern: "https://www.wikidata.org/wiki/{id}",
			Icon: "Database", ValidationRegex: `^Q\d+$`,
			Description: "维基媒体结构化知识图谱实体项 (如 Q11303)",
			SortOrder: 20, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "musicbrainz", NameZh: "MusicBrainz", NameEn: "MusicBrainz",
			Names: models.JSONB{"zh-CN": "MusicBrainz", "en-US": "MusicBrainz"},
			Category: "all", URLPattern: "https://musicbrainz.org/release-group/{id}",
			Icon: "Disc3", ValidationRegex: `^[0-9a-fA-F\-]{36}$`,
			Description: "开放音乐元数据百科全书 (MBID UUID)",
			SortOrder: 30, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "discogs", NameZh: "Discogs", NameEn: "Discogs",
			Names: models.JSONB{"zh-CN": "Discogs", "en-US": "Discogs"},
			Category: "all", URLPattern: "https://www.discogs.com/master/{id}",
			Icon: "Disc", ValidationRegex: `^\d+$`,
			Description: "全球权威黑胶与实体唱片数据库 (Master/Release ID)",
			SortOrder: 40, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "vgmdb", NameZh: "VGMdb", NameEn: "VGMdb",
			Names: models.JSONB{"zh-CN": "VGMdb", "en-US": "VGMdb"},
			Category: "all", URLPattern: "https://vgmdb.net/album/{id}",
			Icon: "Music2", ValidationRegex: `^\d+$`,
			Description: "电子游戏与动漫原声音乐专题数据库",
			SortOrder: 50, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "spotify", NameZh: "Spotify", NameEn: "Spotify",
			Names: models.JSONB{"zh-CN": "Spotify", "en-US": "Spotify"},
			Category: "all", URLPattern: "https://open.spotify.com/album/{id}",
			Icon: "PlayCircle", ValidationRegex: `^[0-9A-Za-z]{22}$`,
			Description: "全球流媒体音乐服务平台 (Album / Artist ID)",
			SortOrder: 60, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "apple_music", NameZh: "Apple Music", NameEn: "Apple Music",
			Names: models.JSONB{"zh-CN": "Apple Music", "en-US": "Apple Music"},
			Category: "all", URLPattern: "https://music.apple.com/album/{id}",
			Icon: "Apple", ValidationRegex: `^\d+$`,
			Description: "苹果音乐数字专辑与创作者页面",
			SortOrder: 70, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "imdb", NameZh: "IMDb", NameEn: "IMDb",
			Names: models.JSONB{"zh-CN": "IMDb 互联网电影资料库", "en-US": "IMDb"},
			Category: "work", URLPattern: "https://www.imdb.com/title/{id}/",
			Icon: "Film", ValidationRegex: `^tt\d+$`,
			Description: "全球权威互联网电影资料库 (如 tt0816692 / nm0000001)",
			SortOrder: 80, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "tmdb", NameZh: "TMDB", NameEn: "The Movie Database",
			Names: models.JSONB{"zh-CN": "TMDB 影视数据库", "en-US": "The Movie Database"},
			Category: "work", URLPattern: "https://www.themoviedb.org/movie/{id}",
			Icon: "Clapperboard", ValidationRegex: `^\d+$`,
			Description: "开放社区影视元数据与海报媒体库",
			SortOrder: 90, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "douban_movie", NameZh: "豆瓣电影", NameEn: "Douban Movie",
			Names: models.JSONB{"zh-CN": "豆瓣电影", "en-US": "Douban Movie"},
			Category: "work", URLPattern: "https://movie.douban.com/subject/{id}/",
			Icon: "Tv", ValidationRegex: `^\d+$`,
			Description: "中文影视与文化评论社区 (条目 ID)",
			SortOrder: 100, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "bangumi", NameZh: "Bangumi 番组计划", NameEn: "Bangumi",
			Names: models.JSONB{"zh-CN": "Bangumi 番组计划", "en-US": "Bangumi"},
			Category: "all", URLPattern: "https://bgm.tv/subject/{id}",
			Icon: "Tv2", ValidationRegex: `^\d+$`,
			Description: "中文 ACG 二次元动画/漫画/游戏/音乐条目索引",
			SortOrder: 110, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "vndb", NameZh: "VNDB 视觉小说数据库", NameEn: "Visual Novel Database",
			Names: models.JSONB{"zh-CN": "VNDB 视觉小说数据库", "en-US": "VNDB"},
			Category: "work", URLPattern: "https://vndb.org/v{id}",
			Icon: "BookHeart", ValidationRegex: `^v?\d+$`,
			Description: "全球权威视觉小说条目数据库 (如 v17)",
			SortOrder: 120, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "steam", NameZh: "Steam", NameEn: "Steam",
			Names: models.JSONB{"zh-CN": "Steam 游戏商店", "en-US": "Steam"},
			Category: "work", URLPattern: "https://store.steampowered.com/app/{id}",
			Icon: "Gamepad2", ValidationRegex: `^\d+$`,
			Description: "Valve 旗下一体化数字游戏分发与社群平台 (App ID)",
			SortOrder: 130, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "anilist", NameZh: "AniList", NameEn: "AniList",
			Names: models.JSONB{"zh-CN": "AniList", "en-US": "AniList"},
			Category: "all", URLPattern: "https://anilist.co/anime/{id}",
			Icon: "Sparkles", ValidationRegex: `^\d+$`,
			Description: "现代动画与漫画社交追踪数据库",
			SortOrder: 140, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "goodreads", NameZh: "Goodreads", NameEn: "Goodreads",
			Names: models.JSONB{"zh-CN": "Goodreads", "en-US": "Goodreads"},
			Category: "work", URLPattern: "https://www.goodreads.com/book/show/{id}",
			Icon: "BookOpen", ValidationRegex: `^\d+.*$`,
			Description: "全球读者书评与阅读记录平台",
			SortOrder: 150, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "douban_book", NameZh: "豆瓣读书", NameEn: "Douban Book",
			Names: models.JSONB{"zh-CN": "豆瓣读书", "en-US": "Douban Book"},
			Category: "work", URLPattern: "https://book.douban.com/subject/{id}/",
			Icon: "Book", ValidationRegex: `^\d+$`,
			Description: "中文书籍条目与读书笔记社区",
			SortOrder: 160, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "isbndb", NameZh: "ISBNdb", NameEn: "ISBNdb",
			Names: models.JSONB{"zh-CN": "ISBNdb 国际标准书号库", "en-US": "ISBNdb"},
			Category: "release", URLPattern: "https://isbndb.com/book/{id}",
			Icon: "Barcode", ValidationRegex: `^[0-9\-]{10,17}$`,
			Description: "国际标准书号全球注册库 (ISBN-10 / ISBN-13)",
			SortOrder: 170, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "isni", NameZh: "ISNI 国际标准名称标识", NameEn: "ISNI",
			Names: models.JSONB{"zh-CN": "ISNI 国际标准名称标识", "en-US": "ISNI"},
			Category: "artist", URLPattern: "https://isni.org/isni/{id}",
			Icon: "UserCheck", ValidationRegex: `^\d{15}[\dX]$`,
			Description: "ISO 国际标准名称标识符 (16 位数字或 X)",
			SortOrder: 180, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "orcid", NameZh: "ORCID 学术学者标识", NameEn: "ORCID",
			Names: models.JSONB{"zh-CN": "ORCID 学者标识", "en-US": "ORCID"},
			Category: "artist", URLPattern: "https://orcid.org/{id}",
			Icon: "GraduationCap", ValidationRegex: `^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$`,
			Description: "全球科研人员与学者开放唯一标识符",
			SortOrder: 190, IsEnabled: true, IsSystem: true,
		},
		{
			Code: "twitter_x", NameZh: "X (Twitter)", NameEn: "X (Twitter)",
			Names: models.JSONB{"zh-CN": "X (原 Twitter)", "en-US": "X (Twitter)"},
			Category: "artist", URLPattern: "https://x.com/{id}",
			Icon: "AtSign", ValidationRegex: `^[A-Za-z0-9_]{1,15}$`,
			Description: "官方社交媒体账号 ID",
			SortOrder: 200, IsEnabled: true, IsSystem: true,
		},
	}
	for _, def := range defs {
		_ = db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "code"}},
			DoUpdates: clause.AssignmentColumns([]string{"name_zh", "name_en", "names", "category", "url_pattern", "icon", "validation_regex", "description", "sort_order", "is_system"}),
		}).Create(&def).Error
	}
}

func seedAttributeSchemas(db *gorm.DB) {
	schemas := []models.EntityAttributeSchema{
		// ── Works (跨媒介作品动态属性) ──
		{
			EntityType:   "work",
			AttributeKey: "engine",
			NameZh:       "游戏引擎 / 开发工具",
			NameEn:       "Game Engine",
			Names:        models.JSONB{"zh-CN": "游戏引擎 / 开发工具", "en-US": "Game Engine", "ja": "ゲームエンジン"},
			DescZh:       "作品底层开发所采用的核心渲染与游戏引擎",
			DescEn:       "Core software engine or framework used to develop the work",
			DataType:     "select",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "Unreal Engine 5", "label_zh": "Unreal Engine 5 (虚幻5)", "label_en": "Unreal Engine 5"},
				map[string]interface{}{"value": "Unreal Engine 4", "label_zh": "Unreal Engine 4 (虚幻4)", "label_en": "Unreal Engine 4"},
				map[string]interface{}{"value": "Unity", "label_zh": "Unity", "label_en": "Unity"},
				map[string]interface{}{"value": "Godot", "label_zh": "Godot Engine", "label_en": "Godot Engine"},
				map[string]interface{}{"value": "RPG Maker", "label_zh": "RPG Maker (RPG制作大师)", "label_en": "RPG Maker"},
				map[string]interface{}{"value": "Ren'Py", "label_zh": "Ren'Py 视觉小说引擎", "label_en": "Ren'Py VN Engine"},
				map[string]interface{}{"value": "Source 2", "label_zh": "Source 2 Engine", "label_en": "Source 2 Engine"},
				map[string]interface{}{"value": "Custom / In-House", "label_zh": "自主研发专有引擎", "label_en": "Custom / In-House Engine"},
			}},
			CategoryFilter: "game",
			DisplayOrder:   10,
			IsSearchable:   true,
			IsEnabled:      true,
			IsSystem:       true,
		},
		{
			EntityType:   "work",
			AttributeKey: "platforms",
			NameZh:       "发行 / 运行平台",
			NameEn:       "Target Platforms",
			Names:        models.JSONB{"zh-CN": "发行 / 运行平台", "en-US": "Target Platforms", "ja": "対応プラットフォーム"},
			DescZh:       "该作品官方支持发布的游戏主机、操作系统与移动设备",
			DescEn:       "Platforms and operating systems officially supported",
			DataType:     "multiselect",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "Windows", "label_zh": "PC (Windows)", "label_en": "PC (Windows)"},
				map[string]interface{}{"value": "macOS", "label_zh": "macOS", "label_en": "macOS"},
				map[string]interface{}{"value": "Linux", "label_zh": "Linux / SteamOS", "label_en": "Linux / SteamOS"},
				map[string]interface{}{"value": "PlayStation 5", "label_zh": "PlayStation 5", "label_en": "PlayStation 5"},
				map[string]interface{}{"value": "PlayStation 4", "label_zh": "PlayStation 4", "label_en": "PlayStation 4"},
				map[string]interface{}{"value": "Nintendo Switch", "label_zh": "Nintendo Switch", "label_en": "Nintendo Switch"},
				map[string]interface{}{"value": "Xbox Series X/S", "label_zh": "Xbox Series X/S", "label_en": "Xbox Series X/S"},
				map[string]interface{}{"value": "iOS", "label_zh": "iOS (iPhone/iPad)", "label_en": "iOS (iPhone/iPad)"},
				map[string]interface{}{"value": "Android", "label_zh": "Android", "label_en": "Android"},
				map[string]interface{}{"value": "WebBrowser", "label_zh": "Web 浏览器", "label_en": "Web Browser"},
			}},
			CategoryFilter: "game",
			DisplayOrder:   20,
			IsSearchable:   true,
			IsEnabled:      true,
			IsSystem:       true,
		},
		{
			EntityType:   "work",
			AttributeKey: "broadcast_season",
			NameZh:       "播出季 / 放送档期",
			NameEn:       "Broadcast Season",
			Names:        models.JSONB{"zh-CN": "播出季 / 放送档期", "en-US": "Broadcast Season", "ja": "放送時期"},
			DescZh:       "动画/剧集的首播年度与季度档期（如 2026年夏季）",
			DescEn:       "Initial release year and broadcast season",
			DataType:     "text",
			CategoryFilter: "anime",
			DisplayOrder:   30,
			IsSearchable:   true,
			IsEnabled:      true,
			IsSystem:       true,
		},
		{
			EntityType:   "work",
			AttributeKey: "production_committee",
			NameZh:       "制作委员会 / 出资企划",
			NameEn:       "Production Committee",
			Names:        models.JSONB{"zh-CN": "制作委员会 / 出资企划", "en-US": "Production Committee", "ja": "製作委員会"},
			DescZh:       "参与出资与联合制作的企划实体（如『○○製作委員会』）",
			DescEn:       "Production consortium or executive committee behind the work",
			DataType:     "text",
			CategoryFilter: "anime",
			DisplayOrder:   40,
			IsSearchable:   true,
			IsEnabled:      true,
			IsSystem:       true,
		},
		{
			EntityType:   "work",
			AttributeKey: "original_medium",
			NameZh:       "原作载体形态",
			NameEn:       "Original Medium",
			Names:        models.JSONB{"zh-CN": "原作载体形态", "en-US": "Original Medium", "ja": "原作媒体"},
			DescZh:       "被改编作品的最初原始诞生载体",
			DescEn:       "Initial origin medium form of the adapted work",
			DataType:     "select",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "light_novel", "label_zh": "轻小说 (Light Novel)", "label_en": "Light Novel"},
				map[string]interface{}{"value": "manga", "label_zh": "漫画 (Manga)", "label_en": "Manga"},
				map[string]interface{}{"value": "game", "label_zh": "电子游戏 (Video Game)", "label_en": "Video Game"},
				map[string]interface{}{"value": "visual_novel", "label_zh": "视觉小说 (Visual Novel)", "label_en": "Visual Novel"},
				map[string]interface{}{"value": "original", "label_zh": "原创企划 (Original)", "label_en": "Original Project"},
				map[string]interface{}{"value": "web_novel", "label_zh": "网络连载小说 (Web Novel)", "label_en": "Web Novel"},
				map[string]interface{}{"value": "stage_play", "label_zh": "舞台剧 / 音乐剧 (Stage Play)", "label_en": "Stage Play"},
			}},
			DisplayOrder: 50,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "work",
			AttributeKey: "bunko",
			NameZh:       "出版文库 / 丛书品牌",
			NameEn:       "Bunko / Imprint",
			Names:        models.JSONB{"zh-CN": "出版文库 / 丛书品牌", "en-US": "Bunko / Imprint", "ja": "文庫レーベル"},
			DescZh:       "出版物所属的文库丛书系列（如电击文库、MF文库J等）",
			DescEn:       "Publishing bunko or book line brand",
			DataType:     "text",
			CategoryFilter: "book",
			DisplayOrder:   60,
			IsSearchable:   true,
			IsEnabled:      true,
			IsSystem:       true,
		},
		{
			EntityType:   "work",
			AttributeKey: "volume_count",
			NameZh:       "总卷数 / 总话数",
			NameEn:       "Total Volumes / Episodes",
			Names:        models.JSONB{"zh-CN": "总卷数 / 总话数", "en-US": "Total Volumes / Episodes", "ja": "総巻数 / 総話数"},
			DescZh:       "已完结或目前累计的单行本总卷数或总放送集数",
			DescEn:       "Total number of completed volumes or episodes",
			DataType:     "number",
			DisplayOrder: 70,
			IsSearchable: false,
			IsEnabled:    true,
			IsSystem:     true,
		},

		// ── Releases (实体规格与发售动态属性) ──
		{
			EntityType:   "release",
			AttributeKey: "rpm",
			NameZh:       "黑胶转速 (RPM)",
			NameEn:       "Vinyl Rotation Speed (RPM)",
			Names:        models.JSONB{"zh-CN": "黑胶转速 (RPM)", "en-US": "Vinyl Rotation Speed (RPM)", "ja": "回転数 (RPM)"},
			DescZh:       "黑胶唱片刻录回放转速（33 1/3 RPM、45 RPM、78 RPM）",
			DescEn:       "Rotations per minute for vinyl phonograph records",
			DataType:     "select",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "33 1/3 RPM", "label_zh": "33⅓ RPM (标准长篇 LP)", "label_en": "33⅓ RPM (Standard LP)"},
				map[string]interface{}{"value": "45 RPM", "label_zh": "45 RPM (高保真 EP / 单曲)", "label_en": "45 RPM (Audiophile EP / Single)"},
				map[string]interface{}{"value": "78 RPM", "label_zh": "78 RPM (老式虫胶 SP)", "label_en": "78 RPM (Shellac SP)"},
			}},
			DisplayOrder: 10,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "release",
			AttributeKey: "matrix_number",
			NameZh:       "母盘矩阵刻模编号 (Matrix Runout)",
			NameEn:       "Matrix / Runout Code",
			Names:        models.JSONB{"zh-CN": "母盘矩阵刻模编号", "en-US": "Matrix / Runout Code", "ja": "マトリクス刻印番号"},
			DescZh:       "压盘压制内圈的物理刻字防伪与版次流水号",
			DescEn:       "Stamped or hand-etched alphanumeric characters in the vinyl runout groove",
			DataType:     "text",
			DisplayOrder: 20,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "release",
			AttributeKey: "disc_color",
			NameZh:       "盘片压制颜色 / 限定材质",
			NameEn:       "Vinyl Color / Special Material",
			Names:        models.JSONB{"zh-CN": "盘片压制颜色 / 限定材质", "en-US": "Vinyl Color / Special Material", "ja": "盤面カラー / 特殊仕様"},
			DescZh:       "彩胶盘片色彩方案（如幻彩透明胶、泼墨大理石纹、Picture Disc）",
			DescEn:       "Custom vinyl compound color or picture disc printing",
			DataType:     "text",
			DisplayOrder: 30,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "release",
			AttributeKey: "packaging_material",
			NameZh:       "装帧与包装形态",
			NameEn:       "Packaging & Box Type",
			Names:        models.JSONB{"zh-CN": "装帧与包装形态", "en-US": "Packaging & Box Type", "ja": "パッケージ仕様"},
			DescZh:       "盒装形态（精装硬盒 Boxset、Digipak 折页、带侧封 OBI、磁吸礼盒等）",
			DescEn:       "Physical packaging format and boxing style",
			DataType:     "select",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "box_set", "label_zh": "精装硬壳收藏盒 (Collector's Box Set)", "label_en": "Collector's Box Set"},
				map[string]interface{}{"value": "digipak", "label_zh": "Digipak 纸质多折封套", "label_en": "Digipak Paper Gatefold"},
				map[string]interface{}{"value": "jewel_case", "label_zh": "Jewel Case 标准 CD/BD 塑料盒", "label_en": "Standard Jewel Case"},
				map[string]interface{}{"value": "gatefold", "label_zh": "Gatefold 双折开页黑胶套", "label_en": "Gatefold Jacket"},
				map[string]interface{}{"value": "steelbook", "label_zh": "SteelBook 典藏铁盒", "label_en": "SteelBook Metal Case"},
				map[string]interface{}{"value": "obi_strip", "label_zh": "带官方日式侧封帯 (OBI)", "label_en": "With Official OBI Strip"},
				map[string]interface{}{"value": "magnetic_box", "label_zh": "磁吸式特装礼盒", "label_en": "Magnetic Clasp Gift Box"},
			}},
			DisplayOrder: 40,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "release",
			AttributeKey: "limited_quantity",
			NameZh:       "全球限量印数 / 份数",
			NameEn:       "Limited Edition Quantity",
			Names:        models.JSONB{"zh-CN": "全球限量印数 / 份数", "en-US": "Limited Edition Quantity", "ja": "限定生産数"},
			DescZh:       "该限定版本在官方公布的全球压制限量份数（如 1000 份）",
			DescEn:       "Total official pressed copies produced globally",
			DataType:     "number",
			DisplayOrder: 50,
			IsSearchable: false,
			IsEnabled:    true,
			IsSystem:     true,
		},

		// ── Artists (创作者动态属性) ──
		{
			EntityType:   "artist",
			AttributeKey: "agency",
			NameZh:       "所属事务所 / 经纪公司",
			NameEn:       "Agency / Management",
			Names:        models.JSONB{"zh-CN": "所属事务所 / 经纪公司", "en-US": "Agency / Management", "ja": "所属事務所"},
			DescZh:       "创作者目前所属的声优/演艺/制作人经纪机构",
			DescEn:       "Current official agency or artist management company",
			DataType:     "text",
			DisplayOrder: 10,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "artist",
			AttributeKey: "official_fanclub",
			NameZh:       "官方粉丝俱乐部 (FC)",
			NameEn:       "Official Fanclub",
			Names:        models.JSONB{"zh-CN": "官方粉丝俱乐部 (FC)", "en-US": "Official Fanclub", "ja": "公式ファンクラブ"},
			DescZh:       "官方粉丝俱乐部名称或会员专区入口",
			DescEn:       "Official fan club name or portal",
			DataType:     "text",
			DisplayOrder: 20,
			IsSearchable: false,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "artist",
			AttributeKey: "active_eras",
			NameZh:       "活跃世代 / 阶段",
			NameEn:       "Active Eras",
			Names:        models.JSONB{"zh-CN": "活跃世代 / 阶段", "en-US": "Active Eras", "ja": "活動年代"},
			DescZh:       "创作者的主力活跃时代（如 90年代黄金期、平成后期、令和期）",
			DescEn:       "Prominent active period or generation",
			DataType:     "text",
			DisplayOrder: 30,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},

		// ── Mediums & Tracks (物理载体与曲目属性) ──
		{
			EntityType:   "medium",
			AttributeKey: "audio_channels",
			NameZh:       "音轨声道布局",
			NameEn:       "Audio Channels",
			Names:        models.JSONB{"zh-CN": "音轨声道布局", "en-US": "Audio Channels", "ja": "音声チャンネル"},
			DescZh:       "主音轨声道排布规范（立体声、5.1环绕声、杜比全景声）",
			DescEn:       "Audio channel layout and spatial format",
			DataType:     "select",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "2.0 Stereo", "label_zh": "2.0 Stereo (两声道立体声)", "label_en": "2.0 Stereo"},
				map[string]interface{}{"value": "5.1 Surround", "label_zh": "5.1 Surround (5.1 环绕声)", "label_en": "5.1 Surround"},
				map[string]interface{}{"value": "7.1.4 Dolby Atmos", "label_zh": "7.1.4 Dolby Atmos (杜比全景声)", "label_en": "7.1.4 Dolby Atmos"},
				map[string]interface{}{"value": "Mono", "label_zh": "1.0 Mono (单声道)", "label_en": "1.0 Mono"},
			}},
			DisplayOrder: 10,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "medium",
			AttributeKey: "sampling_rate",
			NameZh:       "母带采样率与位深",
			NameEn:       "Sampling Rate / Bit Depth",
			Names:        models.JSONB{"zh-CN": "母带采样率与位深", "en-US": "Sampling Rate / Bit Depth", "ja": "サンプリングレート"},
			DescZh:       "数字母带的音频解析力规格（如 96kHz / 24bit、DSD）",
			DescEn:       "Digital audio resolution specifications",
			DataType:     "select",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "44.1kHz / 16bit", "label_zh": "44.1kHz / 16bit (标准 CDDA)", "label_en": "44.1kHz / 16bit (Standard CDDA)"},
				map[string]interface{}{"value": "48kHz / 24bit", "label_zh": "48kHz / 24bit (影视广播标准)", "label_en": "48kHz / 24bit (Broadcast)"},
				map[string]interface{}{"value": "96kHz / 24bit", "label_zh": "96kHz / 24bit (Hi-Res 高解析)", "label_en": "96kHz / 24bit (Hi-Res)"},
				map[string]interface{}{"value": "192kHz / 24bit", "label_zh": "192kHz / 24bit (Ultra Hi-Res)", "label_en": "192kHz / 24bit (Ultra Hi-Res)"},
				map[string]interface{}{"value": "DSD64 (2.8MHz)", "label_zh": "DSD64 2.8MHz (SACD 原生)", "label_en": "DSD64 2.8MHz (Native SACD)"},
				map[string]interface{}{"value": "DSD128 (5.6MHz)", "label_zh": "DSD128 5.6MHz (Double DSD)", "label_en": "DSD128 5.6MHz (Double DSD)"},
			}},
			DisplayOrder: 20,
			IsSearchable: true,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "track",
			AttributeKey: "bpm",
			NameZh:       "曲目速度 (BPM)",
			NameEn:       "Beats Per Minute (BPM)",
			Names:        models.JSONB{"zh-CN": "曲目速度 (BPM)", "en-US": "Beats Per Minute (BPM)", "ja": "テンポ (BPM)"},
			DescZh:       "音乐曲目的节拍速度速度值",
			DescEn:       "Musical tempo measurement in beats per minute",
			DataType:     "number",
			DisplayOrder: 10,
			IsSearchable: false,
			IsEnabled:    true,
			IsSystem:     true,
		},
		{
			EntityType:   "track",
			AttributeKey: "key_signature",
			NameZh:       "调式调号 (Key)",
			NameEn:       "Key Signature",
			Names:        models.JSONB{"zh-CN": "调式调号 (Key)", "en-US": "Key Signature", "ja": "調性 (Key)"},
			DescZh:       "乐曲的主调性（如 C大调、A小调等）",
			DescEn:       "Musical tonality key",
			DataType:     "select",
			Options: models.JSONB{"fields": []interface{}{
				map[string]interface{}{"value": "C Major", "label_zh": "C 大调", "label_en": "C Major"},
				map[string]interface{}{"value": "A Minor", "label_zh": "A 小调", "label_en": "A Minor"},
				map[string]interface{}{"value": "G Major", "label_zh": "G 大调", "label_en": "G Major"},
				map[string]interface{}{"value": "E Minor", "label_zh": "E 小调", "label_en": "E Minor"},
				map[string]interface{}{"value": "D Major", "label_zh": "D 大调", "label_en": "D Major"},
				map[string]interface{}{"value": "B Minor", "label_zh": "B 小调", "label_en": "B Minor"},
				map[string]interface{}{"value": "F Major", "label_zh": "F 大调", "label_en": "F Major"},
				map[string]interface{}{"value": "D Minor", "label_zh": "D 小调", "label_en": "D Minor"},
			}},
			DisplayOrder: 20,
			IsSearchable: false,
			IsEnabled:    true,
			IsSystem:     true,
		},
	}

	for _, s := range schemas {
		var count int64
		db.Model(&models.EntityAttributeSchema{}).Where("entity_type = ? AND attribute_key = ?", s.EntityType, s.AttributeKey).Count(&count)
		if count == 0 {
			_ = db.Create(&s).Error
		}
	}
}

func ApplyPatches(db *gorm.DB) {
	applySchemaPatches(db)
	seedRelationTypes(db)
	seedExternalDatabaseDefinitions(db)
	seedAttributeSchemas(db)
}
