ALTER TABLE mediums DROP CONSTRAINT IF EXISTS mediums_role_valid;
ALTER TABLE mediums DROP CONSTRAINT IF EXISTS mediums_parent_same_release;
ALTER TABLE tracks DROP CONSTRAINT IF EXISTS tracks_parent_same_medium;
DROP TABLE IF EXISTS track_contents;
DROP INDEX IF EXISTS idx_mediums_parent;
DROP INDEX IF EXISTS idx_tracks_parent;
DROP INDEX IF EXISTS idx_mediums_id_release;
DROP INDEX IF EXISTS idx_tracks_id_medium;
ALTER TABLE releases DROP COLUMN IF EXISTS cover_image_url;
ALTER TABLE releases DROP COLUMN IF EXISTS cover_aspect;
ALTER TABLE releases DROP COLUMN IF EXISTS original_language;
ALTER TABLE releases DROP COLUMN IF EXISTS translations;
ALTER TABLE mediums DROP COLUMN IF EXISTS parent_id;
ALTER TABLE mediums DROP COLUMN IF EXISTS number;
ALTER TABLE mediums DROP COLUMN IF EXISTS role;
ALTER TABLE mediums DROP COLUMN IF EXISTS original_language;
ALTER TABLE mediums DROP COLUMN IF EXISTS translations;
ALTER TABLE tracks DROP COLUMN IF EXISTS parent_id;
ALTER TABLE tracks DROP COLUMN IF EXISTS number;
ALTER TABLE tracks DROP COLUMN IF EXISTS original_language;
ALTER TABLE tracks DROP COLUMN IF EXISTS translations;
ALTER TABLE tracks DROP COLUMN IF EXISTS locator;
