-- 由库 owner 显式执行。MCP 运行身份只持自有 schema CRUD，不得获得其它服务角色。
\set ON_ERROR_STOP on
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='mf_mcp') THEN CREATE ROLE mf_mcp LOGIN; END IF;
END $$;
ALTER ROLE mf_mcp NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
\if :{?mcp_password}
SELECT format('ALTER ROLE mf_mcp PASSWORD %L', :'mcp_password') \gexec
\endif
CREATE SCHEMA IF NOT EXISTS mcp;
REVOKE ALL ON SCHEMA mcp FROM PUBLIC;
GRANT USAGE ON SCHEMA mcp TO mf_mcp;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mcp TO mf_mcp;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA mcp TO mf_mcp;
ALTER DEFAULT PRIVILEGES IN SCHEMA mcp GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mf_mcp;
ALTER DEFAULT PRIVILEGES IN SCHEMA mcp GRANT USAGE, SELECT ON SEQUENCES TO mf_mcp;
